name: Build Android APK

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install cython==0.29.36
        pip install buildozer==1.5.0  # Укажите конкретную версию Buildozer
        pip install kivy kivymd

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      with:
        api-level: 36
        components: "platforms;android-36,build-tools;34.0.0,platform-tools" # Убедитесь, что версия build-tools актуальна

    - name: Set ANDROID_HOME environment variable
      run: echo "ANDROID_HOME=$ANDROID_HOME" >> $GITHUB_ENV

    - name: Add Android SDK tools to the PATH
      run: |
        echo "$ANDROID_HOME/platform-tools" >> $GITHUB_PATH
        echo "$ANDROID_HOME/build-tools/34.0.0" >> $GITHUB_PATH # Убедитесь, что версия build-tools соответствует установленной
        echo "$ANDROID_HOME/tools" >> $GITHUB_PATH # Добавляем tools (если нужно)
        echo "$ANDROID_HOME/tools/bin" >> $GITHUB_PATH # Добавляем tools/bin (если нужно)

    - name: Accept Android SDK Licenses
      run: yes | sdkmanager --licenses || true

    - name: Update apt and install dependencies
      run: |
        sudo apt-get update -y
        sudo apt-get install -y git zip unzip openjdk-17-jdk python3-pip autoconf libtool pkg-config zlib1g-dev libffi-dev

    - name: Buildozer Build (initial - to create .buildozer)
      run: buildozer android clean  # Запускаем buildozer, чтобы создать .buildozer

    - name: Set permissions for .buildozer directory
      run: |
        chmod -R 777 .buildozer

    - name: Clean Buildozer cache and directories (after permissions)
      run: |
        rm -rf .buildozer
        rm -rf bin

    - name: Buildozer Build (final)
      run: buildozer android debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: android-app
        path: bin/*debug.apk
