name: Build Android APK

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install cython==0.29.36
        pip install buildozer kivy kivymd

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      with:
        api-level: 36  # Укажите целевой API Level
        components: "platform-tools,platforms;android-36,build-tools;34.0.0" # Добавляем platform-tools и build-tools
        #platform: android-36 # Замените на актуальный android api

    - name: Buildozer Build
      run: |
        sudo apt-get update -y
        sudo apt-get install -y git zip unzip openjdk-17-jdk python3-pip autoconf libtool pkg-config zlib1g-dev libffi-dev
        yes | sdkmanager --licenses || true
        buildozer android debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: android-app
        path: bin/*debug.apk
