name: Deploy Squid Proxy (DO NOT USE FOR PRODUCTION)

on:
  workflow_dispatch:  # Trigger manually for testing

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Update apt-get and install Squid
      run: |
        sudo apt-get update -y
        sudo apt-get install -y squid openssl

    - name: Generate SSL Certificate (Self-Signed - INSECURE)
      run: |
        sudo openssl req -new -x509 -days 365 -nodes -keyout /etc/squid/ssl_cert.pem -out /etc/squid/ssl_cert.pem -subj "/CN=MySquidProxy"

    - name: Configure Squid (VERY BASIC - DO NOT USE AS IS)
      run: |
        sudo echo "http_port 3128" >> /etc/squid/squid.conf
        sudo echo "https_port 3129 cert=/etc/squid/ssl_cert.pem" >> /etc/squid/squid.conf
        sudo echo "http_access allow all" >> /etc/squid/squid.conf
        sudo echo "http_access allow CONNECT all" >> /etc/squid/squid.conf
        sudo echo "always_direct allow all" >> /etc/squid/squid.conf # VERY INSECURE, remove in production
        sudo systemctl restart squid

    - name: Get Public IP
      run: |
        PUBLIC_IP=$(curl ifconfig.me)
        echo "Squid HTTP Proxy IP: $PUBLIC_IP:3128"
        echo "Squid HTTPS Proxy IP: $PUBLIC_IP:3129"
